platform :ios, '17.0'

install! 'cocoapods', :deterministic_uuids => true
project 'LingoPlay.xcodeproj'

target 'LingoPlay' do
  pod 'GoogleMLKit/Translate', '8.0.0'

  target 'LingoPlayTests' do
    inherit! :search_paths
  end
end
